spring:
   mail:
      default-encoding: UTF-8
      host: SERVER_CORREO
      username: TU_CORREO
      password: TU_CLAVE
      port: PUERTO_SERVER_CORREO
      properties:
         mail:
            ssl:
               enable: true
            smtp:
               auth: true
               starttls:
                  enable: true
                  required: true
      protocol: smtp
      test-connection: false